[tool.poetry]
name = "pobeda"
version = "0.1.0"
description = ""
authors = ["Qurlya <pingvining05@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
igraph = "^1.0.0"
matplotlib = "^3.10.8"
networkx = "3.4.2"
pandas = "^3.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
